### ISSUE TITLE
getTransactionReference function in the Response class always returns null

### ISSUE THREAD

**Issue by srishaharidas** [medlmobileenterprises/omnipay-cybersource-so#1]
Currently for the capture request, the response class does not return the transaction reference.

When processing the charge, we get the response from the capture request like so:
```
$response = $gateway->capture($params)->send();
```
We then try to get the transaction reference from this response in order to store it our remoteTransaction object.

```
$remoteTransaction->setRemoteId($response->getTransactionReference());
```

Here, `$response->getTransactionReference()` is returning `null`. Looks like this function has not been implemented in the `Response` class so this defers to the default behavior from `AbstractResponse` which returns `null`.  This function will need to return the request ID from the CyberSource response. This is important since we will need this field to be able to process refunds on this charge

**Comment by dongreenmedl** [comment]
@srishaharidas We have now added the interface to the Response class to properly map the `requestID` from cybersource to act as the `transactionReference`.
